#!/usr/bin/env python
#-*- coding: utf-8 -*-

"""
=head1 NAME

riak_erlang_processes - Plugin to monitor the number of Erlang processes.

=head1 AUTHOR

Hiroaki Sano

=head1 CONFIGURATION

No configuration

=head1 LICENSE

MIT License

=cut
"""

import sys
import requests

def autoconf():
    pass

def get_stats():
    r = requests.get('http://127.0.0.1:8098/stats')
    return r.json()

def config():
    print ('graph_title Erlang processes')
    print ('graph_args --base 1000 -l 0')
    print ('graph_vlabel count')
    print ('graph_category Riak')
    print ('graph_period second')
    print ('graph_info This graph shows the number of Erlang processes')

    print ('erlang_processes.label Erlang processes')
    print ('erlang_processes.type GAUGE')
    print ('erlang_processes.max 1000000')
    print ('erlang_processes.min 0')
    print ('erlang_processes.info The number of Erlang processes')

def main():
    if len(sys.argv) > 1:
        command = sys.argv[1]
    else:
        command = ''

    if command == 'autoconf':
        autoconf()
    elif command == 'config':
        config()
    else:
        ret = get_stats()
        print ('erlang_processes.value %s') % ret['sys_process_count']

if __name__ == '__main__':
    main()
